
# Тут указывается используемый в проекте язык программирования, можно указать несколько
language: python

# Далее, укажите версии python для которых нужно производить сборки
python:
  - "3.7"
  
stage:
  - build
  - execution

install:
# Install libvrt & KVM (see https://github.com/alvistack/ansible-role-virtualbox/blob/master/.travis.yml)
- sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev

# Download Vagrant & Install Vagrant package
- sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
- sudo dpkg -i vagrant_2.2.14_x86_64.deb

# Vagrant correctly installed?
- vagrant --version

#Install vagrant-libvirt Vagrant plugin
#- sudo vagrant plugin install vagrant-libvirt

#Setting up permissions
#- sudo chown -R $USER:$USER ~/.vagrant.d

- sudo apt-get install virtualbox

- vagrant init
- vagrant up
- vagrant ssh -c "ls"

#jobs:
  #include:
    #- stage: build
      #name: general
      #env:
        #- DJANGO_VERSION=2.2.7
      #install:
        #- pip install -q Django==$DJANGO_VERSION
        #- pip install -r requirements.txt
      #script:
        #- vagrant --version
        #- ls -la
    
    #- stage: execution
      #name: test1
      #script: 
        #- bundle install
        #- pip freeze
        #- ls
      
    #- name: test2
      #script:
        #- bundle install
        #- pip freeze
        #- ls
        #- python project/manage.py test
