
# Тут указывается используемый в проекте язык программирования, можно указать несколько
language: python

# Далее, укажите версии python для которых нужно производить сборки
python:
  - "3.7"
  
stage:
  - build
  - execution

install:
  - sudo apt install virtualbox
  - sudo apt install vagrant

jobs:
  include:
    - stage: build
      name: general
      env:
        - DJANGO_VERSION=2.2.7
      install:
        - pip install -q Django==$DJANGO_VERSION
        - pip install -r requirements.txt
        - git clone https://github.com/containernet/containernet.git
      script:
        - vagrant --version
        - ls -la
      cache:
        directories:
          - ./containernet
    
    - stage: execution
      name: test1
      script: 
        - bundle install
        - pip freeze
        - ls
      
    - name: test2
      script:
        - bundle install
        - pip freeze
        - ls
        - python project/manage.py test
