
# Тут указывается используемый в проекте язык программирования, можно указать несколько
language: python

# Далее, укажите версии python для которых нужно производить сборки
python:
  - "3.7"


stages:
  - name: build
    env:
    - DJANGO_VERSION=2.2.7
    install:
    - pip install -q Django==$DJANGO_VERSION
    - pip install -r requirements.txt
    - git clone https://github.com/containernet/containernet.git
    script: python project/manage.py test
